"""add deactivation_date for Users

Revision ID: 0e90732e2027
Revises: de78c86e896b
Create Date: 2021-05-06 14:52:39.120302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e90732e2027'
down_revision = 'de78c86e896b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deactivation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivation_date')
    op.drop_column('users', 'is_deactivated')
    # ### end Alembic commands ###
