"""add auth token

Revision ID: 42820c2dd301
Revises: afcd35c516d0
Create Date: 2021-05-31 14:51:11.743072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42820c2dd301'
down_revision = 'afcd35c516d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
