"""rename WordsBlacklist

Revision ID: 7562b79b5afa
Revises: fdc051097a5c
Create Date: 2021-05-15 10:25:26.339849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7562b79b5afa'
down_revision = 'fdc051097a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('words_blacklist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words_blacklist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('black_words')
    # ### end Alembic commands ###
