"""add right_category for User table

Revision ID: 85cbedac9a52
Revises: 0e90732e2027
Create Date: 2021-05-06 19:25:25.381800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cbedac9a52'
down_revision = '0e90732e2027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('right_category', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'right_category')
    # ### end Alembic commands ###
