"""add WhiteWords table

Revision ID: afcd35c516d0
Revises: c0e58572441d
Create Date: 2021-05-30 21:31:30.906694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcd35c516d0'
down_revision = 'c0e58572441d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('white_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_words')
    # ### end Alembic commands ###
