"""add qa, synonym, black_word rights

Revision ID: c0e58572441d
Revises: 7562b79b5afa
Create Date: 2021-05-16 18:34:10.028814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e58572441d'
down_revision = '7562b79b5afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('right_qa', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('right_synonym', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('right_black_word', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'right_black_word')
    op.drop_column('users', 'right_synonym')
    op.drop_column('users', 'right_qa')
    # ### end Alembic commands ###
