"""add right_users for Users table

Revision ID: de78c86e896b
Revises: dcdd524b76aa
Create Date: 2021-05-06 12:29:38.799242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de78c86e896b'
down_revision = 'dcdd524b76aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('right_users', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'right_users')
    # ### end Alembic commands ###
