"""add WordsBlacklist & SynonymousWords tables

Revision ID: fdc051097a5c
Revises: 44488e46a167
Create Date: 2021-05-10 15:07:35.659762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc051097a5c'
down_revision = '44488e46a167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonymous_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('synonym_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words_blacklist')
    op.drop_table('synonymous_words')
    # ### end Alembic commands ###
